#!/bin/sh

FBSET="/usr/sbin/fbset"
FONT="/usr/share/fonts/liberation/LiberationSans-Regular.ttf"

OMXPLAYER="/usr/bin/omxplayer.bin"

XRES=1920
YRES=1080

if [ -e $FBSET ]; then
  echo 0 >  /sys/class/vtconsole/vtcon1/bind
  fbset -xres 1 -yres 1
fi

$OMXPLAYER --font $FONT "$@"

if [ -e $FBSET ]; then
  fbset -xres ${XRES} -yres ${YRES}
  echo 1 >  /sys/class/vtconsole/vtcon1/bind
fi
